const CATEGORY_DATA = {
  paintings: "paintings",
  "paintings/storyline": "paintings/storyline",
  "paintings/woman": "paintings/woman",
  "paintings/geometric": "paintings/geometric",
  "paintings/abstract": "paintings/abstract",
  "paintings/animal-life": "paintings/animal-life",
  "paintings/architecture": "paintings/architecture",
  "paintings/landscape": "paintings/landscape",
  "paintings/portraits": "paintings/portraits",
  "paintings/still-life": "paintings/still-life",
  "paintings/sufi": "paintings/sufi",
  drawings: "drawings",
  "drawings/woman": "drawings/woman",
  "drawings/abstract": "drawings/abstract",
  "drawings/animal-life": "drawings/animal-life",
  "drawings/architecture": "drawings/architecture",
  "drawings/landscape": "drawings/landscape",
  "drawings/pop-art": "drawings/pop-art",
  "drawings/portraits": "drawings/portraits",
  "drawings/still-life": "drawings/still-life",
  caligraphy: "caligraphy",
  "fabric-products": "fabric-products",
  "fabric-products/shoes": "fabric-products/shoes",
  mandalas: "mandalas",
  modern: "modern",
  religious: "religious",
  cubism: "cubism",
  fantasy: "fantasy",
  graffiti: "graffiti",
  sculpture: "sculpture",
};

module.exports = { CATEGORY_DATA };
